name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: go version
        run: go version
      - name: go fmt
        run: files=$(gofmt -l .); if [[ -n "$files" ]]; then echo -e "::error::go fmt failed\n$files"; exit 1; fi
#      - name: go imports
#        run: |
#          go install golang.org/x/tools/cmd/goimports@latest
#          files=$(goimports -l .); if [[ -n "$files" ]]; then echo -e "::error::go imports failed\n$files"; exit 1; fi
      - name: go test
        run: go test ./... || (echo -e "::error::go tests failed" && exit 1)
