name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - run: |
        go version
        go install golang.org/x/tools/cmd/goimports@latest
        gofmt -l .
        goimports -l .
        go test ./...